# Generated by Django 4.0.5 on 2022-06-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('message_content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
